### ISSUE TITLE
Vue3 + Typescript 4.5 trigger error on slot

### ISSUE THREAD

**Issue by henryavila** [tailwindlabs/headlessui#1087]
**What package within Headless UI are you using?**

https://headlessui.dev/vue/disclosure#styling-an-open-panel

**What version of that package are you using?**

v1.4.2

**What browser are you using?**
Chrome/Edge

**Describe your issue**

I'm using the Disclosure package with the open scope. The code works fine on JS, but if I change the vue component to TS, it trigger the error just in production build. The dev build runs with no error. I have no other error on the app
`TS7031: Binding element 'open' implicitly has an 'any' type.`.

My vue code is
````html
 <Disclosure v-slot="{ open }">
    <DisclosureButton
        :class='open ? "text-black" : "text-gray-500"'
        class="py-2 flex w-full font-semibold justify-between  hover:text-slate-700"
    >
        <span>{{ title }}</span>
        <ChevronRightIcon class="w-6" :class='open ? "transform rotate-90" : ""'/>
    </DisclosureButton>
    <transition
        enter-active-class="transition duration-200 ease-out"
        enter-from-class="transform opacity-0"
        enter-to-class="transform opacity-100"
        leave-active-class="transition duration-100 ease-out"
        leave-from-class="transform opacity-200"
        leave-to-class="transform opacity-0"
    >
        <DisclosurePanel class="">
            .....
        </DisclosurePanel>
    </transition>
</Disclosure>
````

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed, and will be available in the next release.

You can already try it using `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.

**Comment by laurensiusadi** [comment]
I'm on `"@headlessui/vue": "^0.0.0-insiders.591b328"` it's still a problem.

**Comment by Tinoooo** [comment]
The problem still exists for me. The scoped slot bindings seem to have no type.

**Comment by BurningDog** [comment]
I'm on `"@headlessui/vue": "^1.7.16"` and it's still a problem when using `v-slot="{ active }"` on a `ComboboxOption`.

I get this complication error: `TS7031: Binding element 'active' implicitly has an 'any' type.` I only get this error when building Vue in production mode.
