### ISSUE TITLE
Dialog add-padding-to-html technique for scrollbar is problematic and there's no way to control it

### ISSUE THREAD

**Issue by firxworx** [tailwindlabs/headlessui#1319]
Package: @headlessui/react
Version: v1.5.0 (latest at time of writing)
Chrome + Windows 11 (this issue affects many others as well; see description + case)

**Reproduction URL**

Any example of the Dialog component is a valid reproduction: open DevTools and monitor the HTML element while opening a Dialog. 

Refer to the implementation in `dialog.tsx` where the issue behaviour is implemented in a `useEffect()` preceded by the comment line `// Scroll lock`: 

- <https://github.com/tailwindlabs/headlessui/blob/main/packages/@headlessui-react/src/components/dialog/dialog.tsx#L247-L270>

**Issue Description**

The current Dialog implementation makes less-than-ideal assumptions re scrollbars + project CSS and when a Dialog/modal is open, it applies a technique that adds an inline `overflow: hidden` and `padding-right` (with value based on a calculation of scrollbar width) to the document's `<html>` tag.

This results in undesired behaviour / jank in different cases especially on Windows PC's where scrollbars are rather visually imposing.

The lack of control for this behaviour (especially the padding) leaves devs without the ability to more elegantly handle scrollbars and/or handle corner cases or conflicts caused by other styles in a given project.

**Why is this important?**

Scrollbars are a notoriously fickle beast between different OS's and browsers (see: [one example](https://www.filamentgroup.com/lab/scrollbars/) among many articles on the subject). 

I would argue a good reason to [check/switch between Mac + PC](https://twitter.com/adamwathan/status/1453111576173682689?lang=en) when working on front-end projects are the differences in scrollbars between these OS's. Our traffic doesn't always have the same taste in computers vs. many of us web devs :D

**Example case:**

_The following breaks down a single case that is part of a wider issue; refer to linked issue + discussion for related cases._

A straightforward cross-platform-friendly technique to avoid jank during loading + transitions that is particularly gross on Windows is to add `overflow-y: scroll` to the `body` tag. This causes browsers on PC's to always display a scrollbar even when the content fits within the viewport (in this case the scrollbar is present but is presented as disabled/inactive).

This technique is in the `tailwind-preset.js` on several projects I work on and is compatible with many packages/libraries/frameworks to help avoid "jumps" and overall "jank".

However in this case Dialog is **the cause of the very problem it is attempting to prevent**:

![image](https://user-images.githubusercontent.com/24518234/162646775-18cc79be-3eb9-4481-98bc-361f6cb64d33.png)

Content behind the Dialog noticeably "jumps" to the left by the width of the scrollbar.

> In the screenshot we see `padding-right` jumping the content by the width of the scrollbar in both of the following cases: when the content is taller than the viewport (i.e. case for y scrollbar), and when it is shorter (i.e. nothing to scroll).

Confirming:

- when `overflow-y: scroll` is removed from the `body` then Dialog behaves the way that the devs presumably intended (tested on Chrome+PC): no padding or jump is present in the content-fits-window case (no scrollbar visible), and in the content-taller-than-window case (scrollbar visible) the added padding compensates for the scrollbar disappearance resulting from Dialog's addition of `overflow: hidden`.

The presumably-intended behaviour isn't particularly elegant in the content-taller-than-window-case on PC either: 

Windows' imposing scrollbar suddenly disappears and this can result in users' "wtf just blinked"/"jank detection" neurons firing. While a content "jump" is prevented the sudden replacement of the scrollbar with a solid vertical block that doesn't match the app layout isn't much better.

At present, devs have no way to control any of this behaviour if they wish to use Dialog --

Before Dialog is rendered (imposing Windows scrollbar is visible):

![image](https://user-images.githubusercontent.com/24518234/162648096-19be3879-18a5-4ba4-ad0d-f00afb9e61c8.png)

With Dialog modal showing (scrollbar suddenly disappears and it ain't pretty):

![image](https://user-images.githubusercontent.com/24518234/162648122-486d4962-89a4-42d7-8413-71bbc7924e6a.png)

**Expected/Desired Behaviour**

Developers require the ability to control the overflow+padding behaviour of Headless Dialog (e.g. exposed via props)

- Dialog is making an assumption that depends on other CSS in the project being a certain way that may not always hold true
- Devs may disagree with an opinionated technique (e.g. jump avoided but jarring swap of scrollbar may not be desired) and wish to override, but still leverage all the other benefits of Headless + Dialog.

Depending on maintainers' perspective re the presumably-intended behaviour + based on screenshots of it on PC they may wish to classify it as a bug and revisit.

- Different technique(s) or additional case handling (e.g. scrollbar, PC, etc.) could be implemented to improve Dialog in this area

**Related Ideas & Discussions:**

- <https://github.com/tailwindlabs/headlessui/issues/839>
- <https://github.com/tailwindlabs/headlessui/discussions/877>

**Comment by youssefm** [comment]
I just filed this related issue that seems to further support your reasoning:

https://github.com/tailwindlabs/headlessui/issues/1436

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1457, and will be available in the next release.

You can already try it using:

- npm install @headlessui/react@insiders.
- npm install @headlessui/vue@insiders.

Can you double check that this is fixed for you if you install the insiders build?

**Comment by HIT2022** [comment]
Still seeing the same issue that @firxworx descirbed, with @headlessui/react@insiders - 

![image](https://user-images.githubusercontent.com/34664460/193185324-f3252368-ebba-485d-91e9-fde8b42ab108.png)

**Comment by willemmulder** [comment]
This problem still exists. My page jumps and there is a gap on the right side of the screen. I had this

    overflow-y: scroll;

And had to change it into this to fix the problem

```
overflow-y: scroll !important;
padding: 0px !important;
```

**Comment by Anu-cool-007** [comment]
I added the margin to the body instead of HTML which solved the issue.
```
body {
    margin-left: calc(100vw - 100%);
    /* overflow-y: auto !important; */
}
```

**Comment by thisisclint21** [comment]
Yes the problem still exists:

```html
<html lang="en" style="overflow: hidden; padding-right: 15px;">
```

It looks like this:

<img width="201" alt="Screenshot 2022-11-14 at 15 15 33" src="https://user-images.githubusercontent.com/5221349/201682389-266b34c6-467f-4ba7-87cc-b7c04687cd89.png">

To fix it I did this below, but I would prefer don't have this to do:
```scss
html
{
    padding: 0 !important;
}
```

**Comment by amaroyche** [comment]
Same here, just not having a control over Dialog's addition of `overflow: hidden`. This is what is the culprit.
Suggesting to solve this and related issues by giving devs a choice to modify this behavior (leaving default as is).  

```
{
    modifyScrollUnderModal: true,
    modifyScrollUnderModalTag: 'html',
    modifyScrollUnderModalStyles: { overflow: 'hidden' }
}
```

**Comment by EliBates** [comment]
Would also like a way to control this.

**Comment by dbstjddbwls** [comment]
I think this is one of the urgent issues for developers who use headlessui. Has anyone solved this issue?

**Comment by firxworx** [comment]
@RobinMalfait given the comments + activity I think its grounds to reopen this issue?

**Comment by RobinMalfait** [comment]
Can anyone running into this issue open a new issue with a minimal reproduction repo attached that showcases the problem so that we can take a look?

**Comment by hymair** [comment]
I will create an issue, do you have a reproduction template I can use?

<img width="545" alt="image" src="https://user-images.githubusercontent.com/21025134/216354711-abb5fb4c-3fc6-4353-ad96-90d6cd115d0d.png">

**Comment by hymair** [comment]
Had the same issue but upgrading to 1.7.8 fixed it.

**Comment by aaroncemery** [comment]
I'm on 1.7.8 and just ran into this issue.

**Comment by maximedotair** [comment]
Hello ! 1.7.10 and same here

**Comment by RobinMalfait** [comment]
Alright, going to lock this issue. For the people running into this, please open a new issue with a minimal reproduction repo so that we can take a look. Otherwise it is impossible for us to debug what's going on.
