### ISSUE TITLE
Transition still happens even with appear={true}

### ISSUE THREAD

**Issue by wassim** [tailwindlabs/headlessui#1348]
Maybe I've misunderstood the `appear` argument in the Transition component but I would like to show an element with no transition on initial mount if it matches a breakpoint (for example, show a sidebar on larger screens with no transition and toggle it with transition on mobile).

`"@headlessui/react": "^1.5.0"`

```js
<Transition appear={true} show={openMenu || breakpointMatches}>
    <Transition.Child
        enter="transition ease-in-out duration-150 transform"
        enterFrom="translate-x-full"
        enterTo="translate-x-0"
        leave="ease-in-out duration-150 transform"
        leaveFrom="translate-x-0"
        leaveTo="translate-x-full"
        ...
```

**Comment by adamwathan** [comment]
Hey! You want to set appear to `false` if you don’t want it to animate on initial render. Does that solve your problem?

**Comment by RobinMalfait** [comment]
Also make sure to install the insiders build where we fixed a lot of Transition related issues and made it compatible with React 18

**Comment by wassim** [comment]
@adamwathan indeed, the documentation says the default value is `false` so I was confused to see that transition still occurs even when `appear` was set to false. Moving to the insiders build as @RobinMalfait suggested fixed the issue for me!

Thanks!
