### ISSUE TITLE
headlessui-portal-root doesn't delete on modal close (random)

### ISSUE THREAD

**Issue by sgehrman** [tailwindlabs/headlessui#1391]
"@headlessui/react": "^1.6.0",
 
I have a dialog.  I use the sample code on the headless site.

I click a button to open the dialog, and I close it by hitting buttons on the dialog or clicking outside dialog.

I see the headlessui-portal-root appear and disappear, but eventually it gets stuck. headlessui-portal-root stays there and I can't click on my webpage (being blocked by overlay?)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you create a reproduction repo / CodeSandbox and attach it so that we can help you out?

**Comment by soulsam480** [comment]
just saw this issue on my app too. can be reproduced by opening a dialog inside mobile device emulation of inspect element. headless ui version 1.6.0

**Comment by RobinMalfait** [comment]
@soulsam480 can you please provide a reproduction repo / CodeSandbox that showcases this issue? Can't reproduce it: https://headlessui-react-j675qve7g-tailwindlabs.vercel.app/dialog/dialog

**Comment by soulsam480** [comment]
Will do it today.

**Comment by AndysonDK** [comment]
Yeah got the same issue here: https://github.com/AndysonDK/syncbase

**Comment by DanielHoffmann** [comment]
I can confirm this happens on v1.6.0 and on v1.6.1 which was just released. I managed to work around this issue  by using `as="div"` instead of `as={React.Fragment}` in Dialog and Transition

This seems related to the component trying to manually remove actual DOM nodes from the root of the page and React.Fragment doesn't render as a DOM node

Downgrading to v1.5.0 also fixes the problem

**Comment by RobinMalfait** [comment]
This should be fixed by #1432, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.

**Comment by nirix** [comment]
I ran into this issue with v1.6.1. Switching to the insiders version didn't solve the issue.

- React 18.1
- React DOM 18.1
- `@headlessui/react@0.0.0-insiders.bf0d112`

**Comment by RobinMalfait** [comment]
@nirix can you create a reproduction repo so that we can take a look?
