### ISSUE TITLE
Closing Dialog breaks site on Safari

### ISSUE THREAD

**Issue by steventilator** [tailwindlabs/headlessui#1538]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.2

**What browser are you using?**

Safari on iOS 13.2

**Describe your issue**

Closing a dialog in Safari on iOS 13.2 renders my app unusable. The problem seems to be the node `<div id="headlessui-portal-root">...</div>` which stays in the DOM even after closing the dialog. In other browsers, this node is removed from the DOM.

I use the code from the second [Transitions](https://headlessui.dev/react/dialog#transitions) example. The error does not appear if I remove the `<Transition />` components. Although, a new error then arises: A click on the backdrop directly triggers the opening of a new dialog (in my case, behind the backdrop is a grid of avatars which open a dialog when clicked).

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should have been fixed already, try bumping to the latest version 1.6.4.

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

**Comment by TeaBough** [comment]
I'm still having this problem on version `1.6.4` and `1.6.5` of headlessui. It's not working for safari 12.1 (Mojave) but working on safari 13.1 (Catalina)

**Comment by tianyingchun** [comment]
ios 13 while dialog popup, it will block all page click reponding

**Comment by tianyingchun** [comment]
@TeaBough i faced this issue to i use react 18+ 1.6.6. it can not work at ios 3, could you create an demo repo and reopen this issue?
