### ISSUE TITLE
Clicks outside a dialog can trigger elements "behind" the dialog backdrop

### ISSUE THREAD

**Issue by stuikomma** [tailwindlabs/headlessui#1551]
**What package within Headless UI are you using?** @headlessui/react

**What version of that package are you using?** v1.6.4

**What browser are you using?** Reproducible in Chrome on Android and Chrome in Touch Device mode

**Reproduction URL** https://kui8lz.csb.app/

**Describe your issue**

The dialog will immediately reopen if you click the toggle button as you can see in this [video](https://user-images.githubusercontent.com/2040603/171867388-193fba1e-cd74-4d9d-a5aa-d51aa384192a.mov).

This only happens in a specific configuration:
1. The toggle button is visible while the dialog is open. 
2. You tap on the toggle button while the dialog is open.
3. The touchup event happens after the out transition finished. So you either have a fast transition or you tap slowly.
   - the outside-click is handled outside of React callbacks, which is why React does a rerender in the closed state **before** calling the toggle button. This makes the toggle button open the dialog again.

I would expect either
  - the outside click captures the event and my listener on the toggle button is not called OR
  - the toggle button receives the event _while still in the open state_

**Possible fixes**
- We add `event.preventDefault()` [here](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/dialog/dialog.tsx#L225) **this would be my preferred solution, because it emphasizes the "modal" aspect**
  - We make this behavior optIn by adding a prop such as `captureCloseEvent: boolean`
- We pass the event to the onClose function so the lib use can decide what to do
- We use the return value of onClose to decide whether to call `preventDefault` or not

If you tell me which fix you prefer, I'll be happy to make a PR.

----

Thanks for the good work! 🥳

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We just fixed a bunch of outside click related bugs and it is available using the insiders build. I copied your CodeSandbox and bumped `@headlesui/react` to the latest insiders version. CodeSandbox can be found here: https://codesandbox.io/s/fervent-proskuriakova-ylgh92?file=/src/App.tsx

Currently the video doesn't load for me (still processing?) and I can't reproduce it on iOS or on Chrome in Touch Device Mode (haven't tested an Android device yet).

Can you check if the latest insiders version already works automatically for you? If not, then we have some more debugging to do.

**Comment by stuikomma** [comment]
It's working indeed. I also include version `0.0.0-insiders.bdd1b3b` in my project and it works fine. Thanks! 10/10 would recommend 👍🏼 

I noticed one difference: when clicking outside, the dialog now closes on mouseup instead of mousedown, but that behavior is fine by me.

Will this be included in the next release? So I know when to switch back to the official release.

**Comment by RobinMalfait** [comment]
Awesome that it works!

We switched back to a `click` listener (which completes on keyup). This will be included in the next release. Thanks for testing it out!

**Comment by fer-ri** [comment]
> Awesome that it works!
> 
> We switched back to a `click` listener (which completes on keyup). This will be included in the next release. Thanks for testing it out!

Hi, may I know ETA for the next release?

Thanks

**Comment by pavelivanov** [comment]
Hi there, I'm facing same issue on latest: 1.7.17 version. Did this bug was fixed?

**Comment by Fuchsoria** [comment]
> Hi there, I'm facing same issue on latest: 1.7.17 version. Has this bug been fixed?

@latest react version, bug is still here, touch on background will trigger other page elements. On clicks works normally.

**Comment by RealrealChaiR** [comment]
Still running into this on v1.7.19

**Comment by squishydough** [comment]
Still happening in v2.0.0.-alpha.4

**Comment by squishydough** [comment]
Installed v.2.1.2 and the issue went away.
