### ISSUE TITLE
Popover issues with Vue. No visible transition, on headlessui.dev opening

### ISSUE THREAD

**Issue by AdamT** [tailwindlabs/headlessui#1578]
**What package within Headless UI are you using?**

I'm using `"@headlessui/vue": "1.6.1"` but the issue is visible on headlessui.dev.

**What version of that package are you using?**

1.6.1

**What browser are you using?**

Firefox 101, Chrome 102

**Reproduction URL**

The headlessui.dev example codebase. [https://headlessui.dev/vue/popover](https://headlessui.dev/vue/popover)

**Describe your issue**

When visiting [the page](https://headlessui.dev/vue/popover), the vue popover
1. doesn't auto-open.
2. When it is manually clicked it seems to not respond to the first click but then opens on the second click.
3. When it does open it does not appear to have any transitions applied.

https://user-images.githubusercontent.com/641502/173177906-0edb012f-09b5-479b-af8d-c49f0a1a8ceb.mov

**Comment by mathijsfr** [comment]
Same issue here with @headlessui/vue": "^1.6.4"

**Comment by bodograumann** [comment]
I am experiencing the same issue. The user has to click the popover button two times to open it. Not usable :-(

**Comment by bodograumann** [comment]
Ah, so now I see that `isFocusWithinPopoverGroup` actually has a branch to check if the button is being focused.
In reality however, `ownerDocument.value?.activeElement` is the `<body>`, not the button.
Maybe this is related to the surrounding `<iframe>` in the documentation page; as well as in the storybook, where I am doing my tests. :thinking:

**Comment by bodograumann** [comment]
Ah yes. It seems there are multiple `focus` events. First the iframe HTMLDocument is focused, then the Window and finally the button. At least for Firefox. In Chrome the event is not fired for HTMLDocument, but the one for the iframe Window still closes the popover imediately.

Why is this focus event handling even necessary? `Listbox`, which should behave pretty similar to a Popover, does not have it e.g.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The enter transition should work now. https://headlessui.com/vue/popover
If you have other issues, please open a new issue with a reproduction attached 💪

**Comment by joaquin-leimeter** [comment]
I think that the second point of this issue,
`When it is manually clicked it seems to not respond to the first click but then opens on the second click.`
Was not addressed. I am still seeing this issue with Chrome on [https://headlessui.com/vue/popover](https://headlessui.com/vue/popover)

**Comment by bodograumann** [comment]
Seems to work now :rocket:
