### ISSUE TITLE
[Bug][Severe] Using `Combobox.Input` with `displayValue` breaks the input behaviour

### ISSUE THREAD

**Issue by JesusTheHun** [tailwindlabs/headlessui#1735]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

Bug found in : `0.0.0-insiders.fa10cb0`
Works fine with `1.6.6`

**What browser are you using?**

N/A

**Reproduction URL**

https://stackblitz.com/edit/react-onn88a?file=src/App.js

**Describe your issue**

Focus the input and start editing its value. You will see after a few ms it will return to the value returned by `displayValue`. 
Up to `1.6.6` the behaviour was to keep the user input while he's editing.

May be related to issue #1675, PR #1679.

**Comment by thecrypticace** [comment]
This should be fixed by #1755, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`
- `npm install @headlessui/vue@insiders`

**Comment by JesusTheHun** [comment]
Hello @RobinMalfait !

You simplified version do not represent my case.
I have updated my stackblitz to use the latest insider, and the bug is still present.

Click inside the input and start deleting the input content.
First it will close the dropdown, which is weird.
If you focus the input again and try to delete again, you will see the input will always go back to its original value.

**Comment by RobinMalfait** [comment]
@JesusTheHun awesome that it works now!

> EDIT 2 : is it normal that if I focus the input and remove a character, it opens the dropdown and remove the focus from the input ?

Yes and no, typing opens the combobox which is expected behaviour because it then starts filtering. Losing the input focus sounds wrong but it can happen if you render a _different_ input then you rendered before (like a different React tree altogether that was unmounted & re-mounted). You can solve this in 2 ways:

1. Don't render 2 different trees conditionally, but change properties on the same tree.
2. Use the `key` prop to trick React that it is actually the "same" tree even though it is a different tree.

**Comment by RobinMalfait** [comment]
@JesusTheHun This should be fixed by #2090, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.

I've updated your stackblitz reproduction with the latest insiders build: https://stackblitz.com/edit/react-drzwin

**Comment by JesusTheHun** [comment]
@RobinMalfait thanks! Any ETA for the next release ?

**Comment by RobinMalfait** [comment]
@JesusTheHun we are doing a bunch of cleanup this week, so I would say by the end of the week.

**Comment by immaculate656** [comment]
> Hello [@RobinMalfait](https://github.com/RobinMalfait) !
> 
> EDIT : this issue seems solved now. I've just found a new one though 😅 EDIT 2 : is it normal that if I focus the input and remove a character, it opens the dropdown and remove the focus from the input ?





https://shelton-solace787.github.io/MiyPNs82QJaz9Wq0RrXpBFc72fCp/
