### ISSUE TITLE
"Maximum update depth exceeded" when rendering `ListboxOptions` as `Fragment`

### ISSUE THREAD

**Issue by benface** [tailwindlabs/headlessui#3507]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

2.1.9

**What browser are you using?**

All

**Reproduction URL**

https://codesandbox.io/p/sandbox/k7crc9

**Describe your issue**

This is exactly like #3476, but for `ListboxOptions`. Click on the listbox in the CodeSandbox to see the error.

**Comment by snigdha920** [comment]
I downgraded to 2.1.2 and I still have this error.

**Comment by RobinMalfait** [comment]
This should be fixed by #3513, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.

**Comment by ericalli** [comment]
@RobinMalfait I was just digging into this issue as I'm also experiencing it. The insiders version is working for me!

Any rough timeline for the next official release?

**Comment by RobinMalfait** [comment]
@ericalli we just published a new release. `npm install @headlessui/react@latest` should do the trick 👍

**Comment by NadjibBELLOUNDJA** [comment]
@nicolas-rohricht that did the trick for me, thank you, you saved me a lot of time investigating !!

**Comment by Crownpack07** [comment]
We still experiencing this issue on version 2.2.0 and we do not want to remove the transition, Are there plans to fix this still any time soon?
